#ifndef HELLO_RUST_LIB_H
#define HELLO_RUST_LIB_H

/**
 * Autogenerated header by cbindgen
 * Do not edit manually.
 */


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int64_t add(int64_t a, int64_t b);

int64_t subtract(int64_t a, int64_t b);

char *reverse_greet(const char *input);

void free_rust_string(char *ptr);

#endif  /* HELLO_RUST_LIB_H */
